### PR TITLE
Fix map if less than two issues exist

### LINKED ISSUE #10: Fix map if less than two issues exist
The map currently causes a javascript error when no issues exist yet. If only one issue exists, the map does not display anything because invalid map bounds are calculated.

### PR DESCRIPTION
**Pull request by thammerl**
Fixes #10 by

 - using europe bounds if no issues exist yet
 - zooming out a little bit if only a single issue exists

### CODE REVIEW

File: frontend/js/components/map.js [hunk 1]
```diff
@@ -139,15 +138,11 @@ export class LeafletMap extends React.Component {
             return <IssueMarker {...props} />
         })
 
-        let extents = geojsonExtent(JSON.parse(JSON.stringify(geojson)));
```
Comment (thammerl) [inline frontend/js/components/map.js]: Any particular reason for the `JSON.parse(JSON.stringify(...))`? I removed that and just pass the `geojson` object to `geojsonExtent`.

Comment (mcallistersean) [inline frontend/js/components/map.js]: @thammerl Yes, this hack was/is for reasons of immutability, something in the geojsonExtent code changes the actual object. Might be fixed by now

Comment (mcallistersean) [inline frontend/js/components/map.js]: I tried to merge this into master, but had to revert again, because it breaks the loading of issues. For some reason the app starts reloading all issues on every click on an issue on the map.

Comment (thammerl) [inline frontend/js/components/map.js]: I couldn't reproduce this with Google Chrome. Which browser were you using? Did you have to revert the whole pull request or would it have been sufficient to reintroduce the `JSON.parse(JSON.stringify(geojson))`?

Comment (thammerl) [inline frontend/js/components/map.js]: Do you mean the call to `/api` on a click on a marker on the map? It's also doing that for me with the current version.

Comment (thammerl) [inline frontend/js/components/map.js]: This call is probably triggered by the `fetchIssueIfNeeded` action that is raised by `IssueDetailContainer` when the marker is clicked.

See https://github.com/mcallistersean/b2-issue-tracker/blob/master/frontend/js/actions.js#L106.

Comment (mcallistersean) [inline frontend/js/components/map.js]: Yes, you are right.
But there is still some difference in how the map locations are handled. When I have this change in the js code and click a marker, all markers vanish and then re-appear (I guess after loading all issues again, but I'll have to debug to be sure)

Comment (thammerl) [inline frontend/js/components/map.js]: I can't see how my changes could affect the map locations since it's all about the calculation of the map bounds and do not touch the markers at all.

`fetchIssuesIfNeeded` looks like a weird redux action to me. It selects the issue, fetches it again and then fetches all issues again. There isn't even any `if` in there and I don't think a redux action should contain one. Shouldn't it be sufficient to only raise `selectIssue` when a users click a marker? If my understanding of redux is correct, there should be separate `commentDeleted` and `commentAdded` actions if there is a change in the comment list of the issue. As a quickfix, maybe it's possible to dispatch `loadComments` instead of `fetchIssues` in `fetchIssueIfNeeded` and to write a reducer for it (there currently is none for RECEIVE_COMMENTS) in order to just reload the comments?

Comment (mcallistersean) [inline frontend/js/components/map.js]: Just to make sure, you can reproduce the behaviour too?

Comment (mcallistersean) [inline frontend/js/components/map.js]: the fetchIssueIfNeeded is just a stub that can and should be implemented further.
This is the point where we can decide if the issue details should be reloaded (e.g. in response to your suggested commentAdded/Deletred action)

For reasons of simplicity we currently just always load the issue. But I agree, the requestIssues action is not needed there, but it does hide another bug ;-) 
If I remove that then all markers vanish....

Comment (thammerl) [inline frontend/js/components/map.js]: You're right. I didn't notice until now. It happens only because of my removal of `JSON.parse(JSON.stringify())` before passing the geojson to `geojsonExtent`. If I readd it, everything works fine.

Comment (thammerl) [inline frontend/js/components/map.js]: Maybe `Object.assign({}, geojson)` is more idiomatic and efficient by the way.

Comment (mcallistersean) [inline frontend/js/components/map.js]: geoJsonExtent removes the 'id' attribute from each object in features, breaking our stuff ...

Comment (thammerl) [inline frontend/js/components/map.js]: Do you object if I re-revert the pull request and add the `Object.assign`?

Comment (mcallistersean) [inline frontend/js/components/map.js]: Not at all, go ahead

Comment (thammerl) [inline frontend/js/components/map.js]: Done.
